site:
  baseUrl: "https://bot.docs.kotlindiscord.com/"
  theme: "Editorial"

  about:
    siteCopyright: "Kotlin Discord"
    siteDescription: "Kotlin Discord's in-house management bot"
    siteName: "Kotlin Discord: Bot"

kotlindoc:
  name: "Bot"

# This doesn't appear to do anything at the moment, but we can always come back to it
#  args:
#    - "-pass"
#    - "-include"
#    - "./../../../../src/main/kotlin/com/kotlindiscord/bot/package-info.md"

  modules:
    - name: "KDBot"
      sourceDirs: "./../../../../src/main/kotlin"
      moduleGroup: "bot"

  sourcePages:
    menu:
      - type: 'sourcedocPageLinks'
        moduleType: 'kotlindoc'
        itemTitleType: 'SIGNATURE'
        includeItems: true

allPages:
  metaComponents:
    - type: "prism"
      languages:
        - "kotlin"
        - "toml"
        - "yaml"

services:
  publications:
    stages:
      - type: 'githubPages'
        username: 'gdude2002' # the username which created the personal access token
        repo: 'Kotlin-Discord/bot' # the repo to publish to


Editorial:
  primaryColor: "#7289DA"
  legacySearch: false

  social:
    github: "Kotlin-Discord/bot"

  metaComponents:
    - type: "orchidSearch"

  menu:
    - type: "separator"
      title: "API Docs"
      
    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'classes'
      asSubmenu: true
      submenuTitle: 'Classes'

    - type: 'sourcedocPages'
      moduleType: 'kotlindoc'
      node: 'packages'
      asSubmenu: true
      submenuTitle: 'Packages'