name: CI

on:
  push:
    branches-ignore:
      - 'master'

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1.0.0

        with:
          version: 1.11

      - name: Gradle (Build)
        run: sh gradlew generateBuildInfo build docs:orchidBuild

      - name: Rename Artifacts
        run: |
          mv build/libs/*-all.jar build/libs/KDBot.jar
          mv build/libs/*-*.*.jar build/libs/KDBot-slim.jar

      - name: Create Docs Zip
        run: |
          zip -r build/docs.zip docs/build/docs/orchid/*

      - name: Upload artifact (Slim JAR)
        uses: actions/upload-artifact@v1.0.0

        with:
          name: Slim JAR
          path: build/libs/KDBot-slim.jar

      - name: Upload artifact (Production JAR)
        uses: actions/upload-artifact@v1.0.0

        with:
          name: Production JAR
          path: build/libs/KDBot.jar

      - name: Upload artifact (Docs)
        uses: actions/upload-artifact@v1.0.0

        with:
          name: Docs Zip
          path: build/docs.zip
