name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Java
        uses: actions/setup-java@v1.0.0

        with:
          version: 1.11

      - name: Set up Gradle properties
        run: |
          mkdir -p ~/.gradle
          echo "githubToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.gradle/gradle.properties

      - name: Gradle (Build)
        run: sh gradlew build docs:orchidBuild

      - name: Gradle (Deploy docs)
        run: sh gradlew docs:orchidDeploy

      - name: Rename Artifacts
        run: |
          cp build/libs/*-all.jar build/libs/KDBot.jar
          cp build/libs/*-*.*.jar build/libs/KDBot-slim.jar

      - name: Create Docs Zip
        run: |
          zip -r build/docs.zip docs/build/docs/orchid/*

      - name: Upload artifact (Slim JAR)
        uses: actions/upload-artifact@v1.0.0

        with:
          name: Slim JAR
          path: build/libs/KDBot-slim.jar

      - name: Upload artifact (Production JAR)
        uses: actions/upload-artifact@v1.0.0

        with:
          name: Production JAR
          path: build/libs/KDBot.jar

      - name: Upload artifact (Docs)
        uses: actions/upload-artifact@v1.0.0

        with:
          name: Docs Zip
          path: build/docs.zip

      - name: Docker Login
        run: "docker login -u ${{ secrets.MAVEN_USER }} -p ${{ secrets.MAVEN_PASSWORD }} docker.kotlindiscord.com"

      - name: Build Container
        run: "docker build --file Dockerfile -t docker.kotlindiscord.com/bot:latest ."

      - name: Publish Container
        run: "docker push docker.kotlindiscord.com/bot"
