name: Sentry Release

on:
  push:
    branches:
      - master
      - root

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Sentry Release
        run: |
          curl -sL https://sentry.io/get-cli/ | bash

          export SENTRY_RELEASE=$(sentry-cli releases propose-version)

          echo Release: $SENTRY_RELEASE
          echo Project: $SENTRY_PROJECT

          sentry-cli releases new $SENTRY_RELEASE --project $SENTRY_PROJECT
          sentry-cli releases set-commits --auto $SENTRY_RELEASE
          sentry-cli releases finalize $SENTRY_RELEASE

          sentry-cli releases deploys $SENTRY_RELEASE new -e production
          sentry-cli releases finalize $SENTRY_RELEASE
